# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'johndemo.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_JohnDemo(object):
    def setupUi(self, JohnDemo):
        JohnDemo.setObjectName("JohnDemo")
        JohnDemo.resize(462, 336)
        self.centralwidget = QtWidgets.QWidget(JohnDemo)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(80, 50, 276, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(370, 50, 87, 180))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout.addWidget(self.radioButton_3)
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        JohnDemo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(JohnDemo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 462, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuAnimal = QtWidgets.QMenu(self.menubar)
        self.menuAnimal.setObjectName("menuAnimal")
        JohnDemo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(JohnDemo)
        self.statusbar.setObjectName("statusbar")
        JohnDemo.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(JohnDemo)
        self.actionOpen.setObjectName("actionOpen")
        self.actionQuit = QtWidgets.QAction(JohnDemo)
        self.actionQuit.setObjectName("actionQuit")
        self.actionCopy = QtWidgets.QAction(JohnDemo)
        self.actionCopy.setObjectName("actionCopy")
        self.actionCut = QtWidgets.QAction(JohnDemo)
        self.actionCut.setObjectName("actionCut")
        self.actionPaste = QtWidgets.QAction(JohnDemo)
        self.actionPaste.setObjectName("actionPaste")
        self.actionWombat = QtWidgets.QAction(JohnDemo)
        self.actionWombat.setObjectName("actionWombat")
        self.actionPine_marten = QtWidgets.QAction(JohnDemo)
        self.actionPine_marten.setObjectName("actionPine_marten")
        self.actionHoney_badger = QtWidgets.QAction(JohnDemo)
        self.actionHoney_badger.setObjectName("actionHoney_badger")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuAnimal.addAction(self.actionWombat)
        self.menuAnimal.addAction(self.actionPine_marten)
        self.menuAnimal.addAction(self.actionHoney_badger)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuAnimal.menuAction())

        self.retranslateUi(JohnDemo)
        self.actionQuit.triggered.connect(JohnDemo.close)
        QtCore.QMetaObject.connectSlotsByName(JohnDemo)
        JohnDemo.setTabOrder(self.lineEdit, self.radioButton_2)
        JohnDemo.setTabOrder(self.radioButton_2, self.radioButton_3)
        JohnDemo.setTabOrder(self.radioButton_3, self.radioButton)

    def retranslateUi(self, JohnDemo):
        _translate = QtCore.QCoreApplication.translate
        JohnDemo.setWindowTitle(_translate("JohnDemo", "MainWindow"))
        self.label.setText(_translate("JohnDemo", "Whoo-hoo"))
        self.radioButton_2.setText(_translate("JohnDemo", "Weasel"))
        self.radioButton_3.setText(_translate("JohnDemo", "Wolverine"))
        self.radioButton.setText(_translate("JohnDemo", "Fisher"))
        self.menuFile.setTitle(_translate("JohnDemo", "File"))
        self.menuEdit.setTitle(_translate("JohnDemo", "Edit"))
        self.menuAnimal.setTitle(_translate("JohnDemo", "Animal"))
        self.actionOpen.setText(_translate("JohnDemo", "Open..."))
        self.actionQuit.setText(_translate("JohnDemo", "Quit"))
        self.actionCopy.setText(_translate("JohnDemo", "Copy"))
        self.actionCut.setText(_translate("JohnDemo", "Cut"))
        self.actionPaste.setText(_translate("JohnDemo", "Paste"))
        self.actionWombat.setText(_translate("JohnDemo", "Wombat"))
        self.actionPine_marten.setText(_translate("JohnDemo", "Pine marten"))
        self.actionHoney_badger.setText(_translate("JohnDemo", "Honey badger"))

